### ISSUE TITLE
Ensure FileTarget works well with RoadRunner / Swoole

### ISSUE THREAD

**Issue by samdark** [yiisoft/profiler#3]
The following direct `$_SERVER` usage would likely cause issues:

```php
public function export(array $messages): void
    {
        $memoryPeakUsage = memory_get_peak_usage();

        // TODO: make sure it works with RoadRunner and alike servers
        $totalTime = microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'];
```

**Comment by Fantom409** [comment]
I checked this code `microtime(true) - $_SERVER['REQUEST_TIME_FLOAT']` on Roadrunner and Swoole. 
On Roadrunner for 3 different request I received 
`
0.0098521709442139
0.0070569515228271
0.00010180473327637
`. But for Swoole I received `16.071375846863 27.256885051727 32.065992832184`

**Comment by samdark** [comment]
@Fantom409 you've inspired me to write [Swoole tutorial](https://github.com/yiisoft/docs/blob/master/guide/en/tutorial/using-yii-with-swoole.md) and adjust RR tutorial. Thank your for it. Still, this issue isn't related. If you want to continue fiddling with these, please create new issue.

**Comment by samdark** [comment]
$_SERVER['REQUEST_TIME_FLOAT'] seems to be reset for RR for each cycle but Swoole seems to initialize it once. That's why we have the difference.

**Comment by samdark** [comment]
I see two ways solving it:

1. Hacky. `$_SERVER['REQUEST_TIME_FLOAT'] = time()` in `index.php` for each Swoole request.
2. Do not take time from `$_SERVER['REQUEST_TIME_FLOAT']` and take it as an argument.
