### ISSUE TITLE
Support for new psr/log

### ISSUE THREAD

**Issue by tomaszkane** [yiisoft/profiler#44]
New psr/log (2.x and 3.x) supports PHP 8.
Now yiisoft/profiler is fixed to psr/log ^1.1 (PHP 5).

### What steps will reproduce the problem?

Try to `composer update` with yiisoft/profiler when other package require psr/log >= 2.0

### What is the expected result?

Composer update pass, yiisoft/profiler support new psr/log.

### What do you get instead?

Your requirements could not be resolved to an installable set of packages.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.2
| PHP version      | 8.0.x
| Operating system | Linux

**Comment by samdark** [comment]
@tomaszkane do you have some time for a pull request?

**Comment by tomaszkane** [comment]
@samdark In a few days, I will probably find a moment.

**Comment by tomaszkane** [comment]
Added https://github.com/yiisoft/profiler/pull/46
